print("Nama : Gabeta Estefan Sibarani")
print("NIM  : I0322048")
print("Asal : Medan")
print("Deskripsi Kota Asal")
print("Kota Medan merupakan daerah asal sekaligus menjadi kota kelahiranku dimana aku tumbuh dan berkembang.")
print("Medan terletak di salah satu Provinsi yang ada di Pulau Sumatera, yaitu Provinsi Sumatera Utara.")
print("Medan terkenal akan beberapa hal yang menjadi ciri khasnya sendiri. Misalnya, Medan terkenal akan prduksi buah duriannya. Untuk beberapa bulan di musim panen, akan banyak sekali ditemui buah durian deh kualitas yang sangat baik")
print("Selain itu, medan juga memiliki beberapa tempat wisata yang cukup terkenal, salah satunya adalah Danau Toba. Danau Toba merupakan danau terbesar di Indonesia dan bahkan merupakan yang terbesar se-Asia Tenggara. Banyak orang yang memilih Danau Toba sebagai salah satu tujuan wisata yang wajib dikunjungi ketika berada di Sumater Utara.")
print("Dari perkembangannya, Medan termasuk salah satu kota yang cukup modern dengan ekonomi masyarakatnya yang cukup baik pula. Medan juga terkenal akan ciri khas masyarakatnya yang terkesan kasar dengan nada bicaranya yang tinggi. namun pada nyatanya, orang-orang Medan merupakan orang yang ramah dan peduli akan kondisi di sekitarnya. Setiap daerah pasti memiliki oleh-oleh khasnya sendiri, begitu juga dengan Medan yang terkenal akan Bolu Meranti dan Bika Ambon yang sangat lezat.")
print("Harapan Setelah Lulus Dari Teknik Industri UNS")
print("Harapan setelah lulus dari Teknik Industri adalah bisa diterima dan kerja di perusahaan yang bagus dan berhubungan dengan industri, dapat mengaplikasikan pengetahuan yang saya dapat ke dunia kerja, dan jika berkesempatan mungkin akan melanjutkan studi lagi.")
print("Saya juga berharap semoga industri di Indonesia semakin maju, terlebih lagi dengan memajukan kualitas pendidikannya.")